# Generated by Django 4.1.5 on 2023-01-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='authorization',
            field=models.BooleanField(default=False),
        ),
    ]
